### ISSUE TITLE
Is it possible to release it under BSD3 or MIT?

### ISSUE THREAD

**Issue by mrkkrp** [zohl/servant-auth-cookie#4]
Are you sure about GNU GPL v.3?

**Comment by jsl** [comment]
As @mrkkrp mentioned, GPL prevents us from using this (otherwise very useful) library in proprietary programs. If you could confirm whether the use of GPL is intended, it would be very helpful. If this library remains under GPL, we'll have to release our own library for this purpose under a more permissive license. Thanks very much!

**Comment by zohl** [comment]
Hello,

first of all, thank you for reviewing the code and submitting the issues!
I'll try to resolve them as soon as possible, but this may take a while (as I work on it when I have some free time).

I've replaced the license to BSD3, so feel free to use it in your projects (see commit https://github.com/zohl/servant-auth-cookie/commit/6e7d2b1d1e8fd57f3614abbae7251e536438af2c).

**Comment by mrkkrp** [comment]
Thank you very much. If you just check list of active PRs from time to time it's enough, I'll do all the necessary work. Then we can publish a new version and add it to Stackage. Thanks again for changing the license, it's much appreciated!
